### PR TITLE
Support GHC 8.6

### PR DESCRIPTION
**Pull request by ckoparkar**

### CODE REVIEW

**Comment by DanielSchuessler** [comment]
Thanks! Looking at the [changelog](https://github.com/ghc/ghc/blob/ghc-8.6.1-release/libraries/template-haskell/changelog.md), there were apparently no relevant syntax tree changes in `template-haskell-2.14.0.0`, so I can just release this as-is?

**Comment by ckoparkar** [comment]
And the build didn't generate any new warnings either. I'd vote for releasing this in it's current form :)

**Comment by hvr** [comment]
@DanielSchuessler in this case, a revision via

https://hackage.haskell.org/package/th-expand-syns-0.4.4.0/th-expand-syns.cabal/edit

is the more appropriate course of action, as it avoids thrashing binary caches by inflating the versioning configuration space with a redundant new version.

See also https://github.com/haskell-infra/hackage-trustees/blob/master/revisions-information.md for more information

**Comment by DanielSchuessler** [comment]
@hvr: I see! Done.

**Comment by hvr** [comment]
@DanielSchuessler fyi, it already shows up on https://matrix.hackage.haskell.org/package/th-expand-syns

**Pull request merged**
