### PR TITLE
Support template-haskell-2.17.0.0 (ghc-9.0.1-alpha1)

### PR DESCRIPTION
**Pull request by mgsloan**
I didn't see #18 when I wrote this change.  I don't think that change will fully work with the version of template-haskell-2.17 included `ghc-9.0.1-alpha1`.

This also refactors the utilities to avoid using nested CPP as that is quite difficult to read.

### CODE REVIEW

**Comment by mgsloan** [comment]
Can be tested with the following stack.yaml

```yaml
setup-info:
  ghc:
    linux-aarch64:
        9.0.0.20200925:
            url: "https://downloads.haskell.org/ghc/9.0.1-alpha1/ghc-9.0.0.20200925-aarch64-deb9-linux.tar.xz"
            content-length: 313140140
            sha1: 82e235bc168a477bc8e01607748dcc3e1561d020
            sha256: a10621a03d016bc532cc818e2e9e4bcf355b3e09b1b2296958c0111389138854
    linux32:
        9.0.0.20200925:
            url: "https://downloads.haskell.org/ghc/9.0.1-alpha1/ghc-9.0.0.20200925-i386-deb9-linux.tar.xz"
            content-length: 215047224
            sha1: 92ce7ac5fc4a7aeebb9c75abeeb0ddc15affda2c
            sha256: a533641720c33f953ca5d100bc7da219d4cf52eae081c94c97b9ac4cbd9c1d06
    macosx:
        9.0.0.20200925:
            url: "https://downloads.haskell.org/ghc/9.0.1-alpha1/ghc-9.0.0.20200925-x86_64-apple-darwin.tar.xz"
            content-length: 192621180
            sha1: 9aa8ac0add9766a72973d5c498446e1ba7c12b80
            sha256: fb85a78f2bdad53c591261e21c80f3f50fa2b68bbb22632d9be6960af7b27813
    linux64-gmp4:
        9.0.0.20200925:
            url: "https://downloads.haskell.org/ghc/9.0.1-alpha1/ghc-9.0.0.20200925-x86_64-centos7-linux.tar.xz"
            content-length: 202181944
            sha1: 9452c9f13102432cdd9eef2cc745f5dd34b3475b
            sha256: 5f6cd94e0d3917fa5c87031706e665f5d9b997f5c991c9c4c4e2900c39dc98ac
    linux64:
        9.0.0.20200925:
            url: "https://downloads.haskell.org/ghc/9.0.1-alpha1/ghc-9.0.0.20200925-x86_64-deb9-linux.tar.xz"
            content-length: 214032316
            sha1: 7d8127072037427b64a42cefc86fce4e257ac5df
            sha256: d44ab6f933292066d3f4bafc7e1a4209f8044069f9360bd60a97d2de05a73db2
    linux64-tinfo6:
        9.0.0.20200925:
            url: "https://downloads.haskell.org/ghc/9.0.1-alpha1/ghc-9.0.0.20200925-x86_64-fedora27-linux.tar.xz"
            content-length: 216354916
            sha1: 701a5862752f522c70b9c26613edbc3be816850f
            sha256: 2711afabbaab7abd1b8fdf846802ce6ca8e531641d64bbf75780d4de64180dca
    freebsd64:
        9.0.0.20200925:
            url: "https://downloads.haskell.org/ghc/9.0.1-alpha1/ghc-9.0.0.20200925-x86_64-unknown-freebsd.tar.xz"
            content-length: 179380672
            sha1: 48b3bb9eada4c5afa0a6c3974dacdad2c9000870
            sha256: 1e094cbbf9636b1f231bc99e44197fe7a05f570cf46f079bba1a0ca796c3c30c
    windows64:
        9.0.0.20200925:
            url: "https://downloads.haskell.org/ghc/9.0.1-alpha1/ghc-9.0.0.20200925-x86_64-unknown-mingw32.tar.xz"
            content-length: 143960768
            sha1: 4192d866fc6f2e14ffac7a1d5223991a5c3a8dd2
            sha256: 9c0d88165a9ea4b6307a01a356fc4dbf25b101aabe1694c576986f7a678e30f7

resolver: ghc-9.0.0.20200925
compiler: ghc-9.0.0.20200925
compiler-check: match-exact
packages:
- .
extra-deps:
- git: https://github.com/dreixel/syb
  commit: 95798bd73bc431e67b462573d181f9e0ab0dc497
```

**Comment by RyanGlScott** [comment]
It might be worth using the  [`th-abstraction`](http://hackage.haskell.org/package/th-abstraction-0.4.2.0/docs/Language-Haskell-TH-Datatype-TyVarBndr.html) library to minimize the amount of CPP needed to support the changes to `TyVarBndr`. Here is what this patch would be with `th-abstraction`:

```diff
diff --git a/Language/Haskell/TH/ExpandSyns.hs b/Language/Haskell/TH/ExpandSyns.hs
index c443722..848d7dc 100644
--- a/Language/Haskell/TH/ExpandSyns.hs
+++ b/Language/Haskell/TH/ExpandSyns.hs
@@ -12,6 +12,7 @@ module Language.Haskell.TH.ExpandSyns(-- * Expand synonyms
                                      ,substInCon
                                      ,evades,evade) where
 
+import Language.Haskell.TH.Datatype.TyVarBndr
 import Language.Haskell.TH.ExpandSyns.SemigroupCompat as Sem
 import Language.Haskell.TH hiding(cxt)
 import qualified Data.Set as Set
@@ -30,16 +31,15 @@ packagename = "th-expand-syns"
 
 
 -- Compatibility layer for TH >=2.4 vs. 2.3
-tyVarBndrGetName :: TyVarBndr -> Name
+tyVarBndrGetName :: TyVarBndr_ flag -> Name
 #if !MIN_VERSION_template_haskell(2,10,0)
 mapPred :: (Type -> Type) -> Pred -> Pred
 #endif
 bindPred :: (Type -> Q Type) -> Pred -> Q Pred
-tyVarBndrSetName :: Name -> TyVarBndr -> TyVarBndr
+tyVarBndrSetName :: Name -> TyVarBndr_ flag -> TyVarBndr_ flag
 
 #if MIN_VERSION_template_haskell(2,4,0)
-tyVarBndrGetName (PlainTV n) = n
-tyVarBndrGetName (KindedTV n _) = n
+tyVarBndrGetName = tvName
 
 #if MIN_VERSION_template_haskell(2,10,0)
 bindPred = id
@@ -51,8 +51,7 @@ bindPred f (ClassP n ts) = ClassP n <$> mapM f ts
 bindPred f (EqualP t1 t2) = EqualP <$> f t1 <*> f t2
 #endif
 
-tyVarBndrSetName n (PlainTV _) = PlainTV n
-tyVarBndrSetName n (KindedTV _ k) = KindedTV n k
+tyVarBndrSetName n = mapTVName (const n)
 #else
 
 type TyVarBndr = Name
@@ -390,6 +389,10 @@ expandSynsWith settings = expandSyns'
       go acc x@ForallVisT{} = forallAppError acc x
 #endif
 
+#if MIN_VERSION_template_haskell(2,17,0)
+      go acc x@MulArrowT = passThrough acc x
+#endif
+
 -- | An argument to a type, either a normal type ('TANormal') or a visible
 -- kind application ('TyArg').
 data TypeArg
@@ -462,6 +465,10 @@ instance SubstTypeVariable Type where
           ForallVisT vars' (doSubsts vts' body)
 #endif
 
+#if MIN_VERSION_template_haskell(2,17,0)
+      go MulArrowT = MulArrowT
+#endif
+
 -- testCapture :: Type
 -- testCapture =
 --     let
@@ -542,7 +549,7 @@ instance SubstTypeVariable Con where
 
 
 class HasForallConstruct a where
-    mkForall :: [TyVarBndr] -> Cxt -> a -> a
+    mkForall :: [TyVarBndrSpec] -> Cxt -> a -> a
 
 instance HasForallConstruct Type where
     mkForall = ForallT
@@ -555,8 +562,8 @@ instance HasForallConstruct Con where
 -- Apply a substitution to something underneath a @forall@. The continuation
 -- argument provides new substitutions and fresh type variable binders to avoid
 -- the outer substitution from capturing the thing underneath the @forall@.
-commonForallCase :: (Name, Type) -> [TyVarBndr]
-                 -> ([(Name, Type)] -> [TyVarBndr] -> a)
+commonForallCase :: (Name, Type) -> [TyVarBndr_ flag]
+                 -> ([(Name, Type)] -> [TyVarBndr_ flag] -> a)
                  -> a
 commonForallCase vt@(v,t) bndrs k
             -- If a variable with the same name as the one to be replaced is bound by the forall,
diff --git a/testing/Main.hs b/testing/Main.hs
index d91f25f..f22c6b5 100644
--- a/testing/Main.hs
+++ b/testing/Main.hs
@@ -5,6 +5,7 @@
 {-# LANGUAGE CPP #-}
 -- {-# OPTIONS -ddump-splices #-}
 
+import Language.Haskell.TH.Datatype.TyVarBndr
 import Language.Haskell.TH.ExpandSyns
 import Language.Haskell.TH
 import Language.Haskell.TH.Syntax
@@ -31,9 +32,9 @@ main = do
 
 -- See comment about 'PlainTV'/'KindedTV' above
 #if MIN_VERSION_template_haskell(2,10,0)
-        y_0 = KindedTV (mkName "y_0") StarT
+        y_0 = kindedTVSpecified (mkName "y_0") StarT
 #else
-        y_0 = PlainTV (mkName "y_0")
+        y_0 = plainTVSpecified (mkName "y_0")
 #endif
 
         expectedExpansion =
diff --git a/testing/Types.hs b/testing/Types.hs
index fcc4e65..c644556 100644
--- a/testing/Types.hs
+++ b/testing/Types.hs
@@ -5,6 +5,7 @@
 module Types where
 
 import Language.Haskell.TH
+import Language.Haskell.TH.Datatype.TyVarBndr
 import Language.Haskell.TH.Syntax
 import Util
 
@@ -19,7 +20,7 @@ type Int'' = Int
 type Id a = a
 
 -- type E x = forall y. Either x y -> Int
-$(sequence [tySynD (mkName "E") [PlainTV (mkName "x")]
+$(sequence [tySynD (mkName "E") [plainTV (mkName "x")]
                 (forallT'' ["y"] (conT ''Either `appT` varT' "x" `appT` varT' "y" --> conT ''Int))
            ])
 
diff --git a/testing/Util.hs b/testing/Util.hs
index 2a5622d..a3cf854 100644
--- a/testing/Util.hs
+++ b/testing/Util.hs
@@ -2,6 +2,7 @@
 {-# LANGUAGE TemplateHaskell #-}
 module Util where
 import           Language.Haskell.TH
+import           Language.Haskell.TH.Datatype.TyVarBndr
 import           Language.Haskell.TH.ExpandSyns
 
 mkTest ::  Q Type -> Q Type -> Q Exp
@@ -16,11 +17,19 @@ mkTest input expected =
       if (pprint expected'==pprint actual) then [| putStrLn "Ok" |] else [| error "expected /= actual" |]
 
 
-forallT' xs = forallT ((PlainTV . mkName) `fmap` xs)
+forallT' :: [String] -> Q Cxt -> Q Type -> Q Type
+forallT' xs = forallT ((plainTVSpecified . mkName) `fmap` xs)
+
+forallT'' :: [String] -> Q Type -> Q Type
 forallT'' xs = forallT' xs (cxt [])
+
+varT' :: String -> Q Type
 varT' = varT . mkName
+
+conT' :: String -> Q Type
 conT' = conT . mkName
 
+(-->) :: Q Type -> Q Type -> Q Type
 x --> y = (arrowT `appT` x) `appT` y
 infixr 5 -->
 
diff --git a/th-expand-syns.cabal b/th-expand-syns.cabal
index 438577b..56567c4 100644
--- a/th-expand-syns.cabal
+++ b/th-expand-syns.cabal
@@ -23,7 +23,8 @@ source-repository head
  location: git://github.com/DanielSchuessler/th-expand-syns.git
 
 Library
-    build-depends:       base >= 4 && < 5, template-haskell < 2.18, syb, containers
+    build-depends:       base >= 4 && < 5, template-haskell < 2.18, syb, containers,
+                         th-abstraction >= 0.4 && < 0.5
     ghc-options:
     exposed-modules:     Language.Haskell.TH.ExpandSyns
     other-modules:       Language.Haskell.TH.ExpandSyns.SemigroupCompat
@@ -33,4 +34,4 @@ Test-Suite test-th-expand-syns
     hs-source-dirs:     testing
     main-is:            Main.hs
     other-modules:      Util, Types
-    build-depends:      base, th-expand-syns, template-haskell
+    build-depends:      base, th-expand-syns, template-haskell, th-abstraction
```

**Comment by mgsloan** [comment]
Nice, I like that :+1:

**Comment by DanBurton** [comment]
Bump. I can confirm that using the version of `th-expand-syns` from this PR allows `haskell-src-meta` to compile and pass its test suite with ghc 9.0.1

**Comment by konn** [comment]
Is there any plan to merge either this or #18? I confirmed that at least this (#19) PR works just fine with GHC >= 9.

**Comment by DanielSchuessler** [comment]
Sorry for the late response. Since I'm currently not properly maintaining this package, I'd like to transfer maintainership of it to interested members of the community :)

**Comment by RyanGlScott** [comment]
I'm a maintainer of a library that indirectly depends on `th-expand-syns`, so I'd be interested in picking up maintainership.

That being said, I am _also_ a maintainer of another library, [`th-abstraction`](http://hackage.haskell.org/package/th-abstraction), which independently developed [machinery for expanding type synonyms](http://hackage.haskell.org/package/th-abstraction-0.4.2.0/docs/Language-Haskell-TH-Datatype.html#v:resolveTypeSynonyms). One long-term goal I would have as a maintainer is to ensure that `th-abstraction` has feature parity with `th-expand-syns` and make the latter library a thin layer on top of the former library. That way, we wouldn't have to independently maintain two codebases that do essentially the same thing.

**Comment by DanielSchuessler** [comment]
@RyanGlScott: Added you to the maintainer group on Hackage, thanks :)

**Pull request merged**
